name: discomposed
description: A library that composes together some of the common service discovery techniques for local networking.
version: 0.0.1-alpha03
repository: https://github.com/davehancock/discomposed
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto:
  flutter_nsd:
    path: ../flutter_nsd
  multicast_dns:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
